# Generated by Django 2.2.6 on 2019-10-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('constent', models.TextField(max_length=200, verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='portafolio', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'portafolio',
                'ordering': ['-created'],
            },
        ),
    ]
