# Generated by Django 2.2.6 on 2019-10-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portafolio',
            old_name='constent',
            new_name='content',
        ),
    ]
