# Generated by Django 2.2.6 on 2019-10-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created'], 'verbose_name': 'Acerca de', 'verbose_name_plural': 'about'},
        ),
    ]
