# Generated by Django 2.2.6 on 2019-10-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs', verbose_name='Imagen'),
        ),
    ]
